//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Ecomerce2019Entities : DbContext
    {
        public Ecomerce2019Entities()
            : base("name=Ecomerce2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<tb_admin> tb_admin { get; set; }
        public virtual DbSet<tb_Categoria> tb_Categoria { get; set; }
        public virtual DbSet<tb_Cliente> tb_Cliente { get; set; }
        public virtual DbSet<tb_ClienteEx> tb_ClienteEx { get; set; }
        public virtual DbSet<tb_DetalleEnvio> tb_DetalleEnvio { get; set; }
        public virtual DbSet<tb_detalleOrden> tb_detalleOrden { get; set; }
        public virtual DbSet<tb_Distrito> tb_Distrito { get; set; }
        public virtual DbSet<tb_Doctor> tb_Doctor { get; set; }
        public virtual DbSet<tb_Horario> tb_Horario { get; set; }
        public virtual DbSet<tb_ListaDeseos> tb_ListaDeseos { get; set; }
        public virtual DbSet<tb_ListaDeseosExt> tb_ListaDeseosExt { get; set; }
        public virtual DbSet<tb_Orden> tb_Orden { get; set; }
        public virtual DbSet<tb_OrdenExt> tb_OrdenExt { get; set; }
        public virtual DbSet<tb_Pago> tb_Pago { get; set; }
        public virtual DbSet<tb_TipoPago> tb_TipoPago { get; set; }
        public virtual DbSet<tb_VistaReciente> tb_VistaReciente { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_cod()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_cod");
        }
    
        public virtual ObjectResult<sp_listaDistrito_Result> sp_listaDistrito()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listaDistrito_Result>("sp_listaDistrito");
        }
    
        public virtual ObjectResult<sp_reportez_Result> sp_reportez(Nullable<int> cod, Nullable<int> codb)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            var codbParameter = codb.HasValue ?
                new ObjectParameter("codb", codb) :
                new ObjectParameter("codb", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reportez_Result>("sp_reportez", codParameter, codbParameter);
        }
    }
}
